/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef sync_CONSTANTS_H
#define sync_CONSTANTS_H

#include "sync_types.h"



class syncConstants {
 public:
  syncConstants();

};

extern const syncConstants g_sync_constants;



#endif
